require:
  - rubocop-rails

AllCops:
 NewCops: enable
 TargetRubyVersion: 3.0.1
 Exclude:
   - 'bin/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'node_modules/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'
   - 'spec/spec_helper.rb'
   - 'vendor/**/*'

Style/ClassAndModuleChildren:
 EnforcedStyle: 'compact'

Style/Documentation:
 Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false

Metrics/BlockLength:
 IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
